build:
	g++ crypto.cpp -o crypto
	g++ valley.cpp -o valley
	g++ stocks.cpp -o stocks
	g++ ridge.cpp -o ridge

run-p1:
	./crypto

run-p2:
	./stocks

run-p3:
	./valley

run-p4:
	./ridge

clean:
	rm ./crypto
	rm ./stocks
	rm ./valley
	rm ./ridge